server:
  port: 8091

spring:
  application:
    name: front-provider
  data:
    solr:
      # host: http://127.0.0.1:8080/solr/zzj2
      repositories:
        enabled: true
      zk-host: 192.168.31.82:2181,192.168.31.82:2182,192.168.31.82:2183
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.10:3306/education?useUnicode=true&characterEncoding=utf-8
    username: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000





