eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8092
  max-http-header-size: 4048576

spring:
  application:
    name: front-comsumer
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html


ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
redis:
  host: 127.0.0.1
  maxActive: 600
  maxIdle: 300
  maxWait: 1000
  pass: ''
  port: 6379
  testOnBorrow: true


#feign:
#  hystrix:
#    enabled: true

#  httpclient:
#    enabled: true


