eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8082
spring:
  application:
    name: service-comsumer
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
    data:
      mongodb:
        database: education
        host: 127.0.0.1:27017





#feign:
#  hystrix:
#    enabled: true

#  httpclient:
#    enabled: true

